"""Initial migrations.

Revision ID: 159b60132535
Revises: 
Create Date: 2015-12-04 21:53:17.278656

"""

# revision identifiers, used by Alembic.
revision = '159b60132535'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskid', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_details')
    ### end Alembic commands ###
