"""Added family, arch fields in Job table.

Revision ID: 55932e5d6b3f
Revises: 159b60132535
Create Date: 2015-12-05 12:44:33.525292

"""

# revision identifiers, used by Alembic.
revision = '55932e5d6b3f'
down_revision = '159b60132535'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_details', sa.Column('arch', sa.String(length=255), nullable=True))
    op.add_column('job_details', sa.Column('family', sa.String(length=255), nullable=True))
    op.add_column('job_details', sa.Column('release', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_details', 'family')
    op.drop_column('job_details', 'arch')
    op.drop_column('job_details', 'release')
    ### end Alembic commands ###
